name: Build IPA

# Trigger the workflow on push to main or manually
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Make the script executable
      - name: Make ipabuild.sh executable
        run: chmod +x ./ipabuild.sh

      # 3. Run your IPA build script
      - name: Run IPA Build Script
        run: ./ipabuild.sh
